version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - sudo pip install boto3
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_1.5.7_linux_amd64.zip
      - apt-get update
      - apt-cache search source
      - apt-get install -y curl jq
      - echo "Prepare terraform file"
      - cd terraform-code
      - echo "terraform { " >> provider-output-backend.tf
      - echo "   backend \"s3\" { " >> provider-output-backend.tf
      - echo "   bucket = \"$datapart.$region.terraform-state-software\"" >> provider-output-backend.tf
      - echo "   key    = \"$applicationname/terraform.tfstate\"" >> provider-output-backend.tf
      - echo "   region = \"$region\"" >> provider-output-backend.tf
      - echo "  }" >> provider-output-backend.tf
      - echo "}" >> provider-output-backend.tf
      - cat provider-output-backend.tf
      - terraform init
  build:
    commands:
      - terraform plan
      - echo "Post apply build"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
